---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAZPMJFAzPigljpXyrk/DAAGzkdUvnb2nGP2bDTzrGXeEg8Dn205tvnTRstFKVfQwQQ1Def0UtMbJKO/gdUJdzGFwiiwFdPi0sIo58Z0c6MzLK4cHOux9Mxzf8F8ze+VhClazsOeKarkdKuC3nHVf4m0BCba5LztAJSVYB/XvR+VdR2vwcoHkYJfHpTre8T71aeiE+c9RLTj3P7Q2RIiXOrvqBVqN97aNAEZo0y6B6bH79MpPzoasOnGRkNWm6bZYxIoC4aEIblj7scrL/QdwABuQjYIiZEaEMuEJSR+t9Ueo1priTboulWPqKKsKXon+yaG3eJ/KY3Jpg+t2twS16QEyIYCZatABzrdN8STErXx4R/hG6tP0aFWmjbEIzevBm/IzXvS45GsQuGduZC77FvUpYOBqFxw3CWYB8wQn07mKu7YGchnLid+ow1cp2QChIF6AcN2EAO62GUtpZbGQ8yD8vsf1+y27ippDByMHzZEybUZRDiEbkZJ7tJCpIg8XrFr/wUp/0k+9/ymf4Q860y+1MZwDysu1pevnl1FnUq8jGChJ4vAl1dZdfOk8QJhhG/vZHL5lvWL7EbfiQCafE2T65bBeqejzjj95JeOqWx9XbZBx1jSEtAFVhu9VgyXmGJANLMcUVmbzH+oR9O2Nx5T3j759ltRG40XJP3SDSRELetgeYnrVLJaPgEPEfNHUi7wsgnjeyDV2upoCjsrSA7Nv8Qe0I8Ur4A/FlSvAhlsl8O4FzvzXVx7yN0LCDOuGfyjnb9eQ==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
