---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCBjPer8CfyKova/2pSPrQcSARevN1UEb0vmvzbJgdk9WxyAsQ3gJngRFnuyAUfB8S9s/t4OkcZ+3QE8VAQ2bzGarBq7IMlopSdbxCwkCy5x8BSthNgEYv+3uWxe+r5aiVWCETlkLoJzemNfUYikXlWcSRqQejKjeAxOVP/UHFSfr9bdxlb3rkGhNnbEiInM9Hdhkv40LJHCeFfBkFEYiboGlVZevgjQ3KnifrgeKv/b+SZ/G52qTXKt/jiSJRS8hgOLrZ5ZZWgX69sej3Uq9EMhUBic54UxHvVfnvK3nmhl8rOJC4BkV/NSmklfncAE6gTsp6L+gXB8mgoPylqUCjf4SJZFEmtXT4XEy2xvLea1yhVlGcy+pzNsyVFVCJ/XiKmfv5jlNSNgNw8v7O/WTBI2W4pmie6JP0078gueTp1KNQ9EkU67xTCj7BaFw4G2LhFY2oJn67wNxPI6PQVkhxoJUyKhfurvIqiMYAQ1uKXkxm/+QqJ9tPNDNbfE+BUL9w24ElToaxGoh/aIt70CcVbvqnrvYiEGby8/P/vij3rnSHMq7ENhRkWlorafGoGzBfmTaOoMShsVYy2Jd4fVeacbnLRCZHfMcDW7dd6a4k87Bi98aro7FVl6MiCZaSaUsUq8AK8UgziVrDc1TwffsqcJqQE+7JanWikF5WeZMWbae83wc0yakWAnp5Gme25zZEQPuLTB/uumS3RKplHNIYWjY65piKP8hHHf1ga
    admin-user: AgARDBn8eZcIdWPnZqk7fAZflsSKAv2zpaLe7eR3+LHcQGMZ7H/35azOHsNADcPjzqe3dfPOH30ddeOAovh+16056V1bUZ+TUg0ABONsPw8No9166SbKVEpLsH28etMD4iNp2uuCkMpsTW7/Wg4KBbf6MH7x0Wk2Paahz+1PsgLd6Xyvo46JmEvefi1LSPeDZHv7ZfoaGpqdfjBjgZkTU7RSFtA937QgGUH8tRnwxei9uFHWeF5c8QBtKmy7s4z8UQ8HsdCq5Jf4w5Hrcm9RPtC+58wsGbO4ZDv0X6+c3g+AITzeYC2BRuoNy15ja51pXVkuBHUhtoe+ijQJMM7VSxV/qlxVde1eH9gB2+K3RmH3lRzoisABEGPBzt+Cc091/P/vrox2hjkNAnlcFXJ8Pji/73c3+ooQ4YErpWRk6q+cZRyuuMEI+qNUYAVRTF182/0jAwBFGIsFhP8SzTgbjV2ejfzVBs5wLsPip8VmCgsj0jqWqA882vqRgLMG1K9d45kyoKUyEOsSzFGaOF5zTOr8Yy7+bNC5q/nHW3oQb6KxFSSzonq6HAdjWpu9nbwSm37ThEIUJ9pmdQ905GY9NRTOk6/f78hCctp/cymL0gM4ANkatGA9nClBIsIuQ9UXELixYTrJ48n+29BG/EzhvUlxEpldvYai7+KMlTrihgovP4ea0Fsc0RKia0fnSGkJaIqcnjRvJA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
